SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCT](
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[PRODUCT_NAME] [nvarchar](25) NULL,
	[QUANTITY] [numeric] NULL,
	[MODIFIED_DATE] [datetime] NULL)
GO
ALTER TABLE [dbo].[PRODUCT] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO
